apiVersion: v1
kind: Service
metadata:
  name: vprocache01 # app calls this domain in application.properties
spec:
  selector:
    app: vpromc # label of pod
  ports:
  - port: 11211
    targetPort: vpromc-port
    protocol: TCP
  type: ClusterIP
