apiVersion: v1
kind: Service
metadata:
  name: vpromq01 # app calls this domain in application.properties
spec:
  selector:
    app: vpromq01 # label of pod
  ports:
  - port: 15672
    targetPort: vpromq01-port
    protocol: TCP
  type: ClusterIP
